#ifndef GUARD_CONSTANTS_GAME_PROGRESS_H
#define GUARD_CONSTANTS_GAME_PROGRESS_H

enum GameProgress {
    GP_NOT_STARTED,
    GP_BOAT_ROOM,
    GP_BEFORE_PICK_STARTER,
    GP_PICKING_STARTER,
    GP_LEFT_BOAT,
    GP_HORIZON_PORT_RIVAL_ENCOUNTERED,
    GP_REST_AREA_1_ENCOUNTERED,
    
};

#endif