CrownForestNorth_MapScripts::
	.byte 0


CrownForestNorth_BugManiac::
# 4 "data/maps/CrownForestNorth/scripts.pory"
	trainerbattle_single TRAINER_CROWN_NORTH_BUG_MANIAC, CrownForestNorth_BugManiac_Text_0, CrownForestNorth_BugManiac_Text_1
# 9 "data/maps/CrownForestNorth/scripts.pory"
	msgbox CrownForestNorth_BugManiac_Text_2, MSGBOX_NPC
	return


CrownForestNorth_Hiker::
# 13 "data/maps/CrownForestNorth/scripts.pory"
	trainerbattle_single TRAINER_CROWN_NORTH_HIKER, CrownForestNorth_Hiker_Text_0, CrownForestNorth_Hiker_Text_1
# 18 "data/maps/CrownForestNorth/scripts.pory"
	msgbox CrownForestNorth_Hiker_Text_2, MSGBOX_NPC
	return


CrownForestNorth_BlackBelt::
# 22 "data/maps/CrownForestNorth/scripts.pory"
	trainerbattle_single TRAINER_CROWN_NORTH_BLACKBELT, CrownForestNorth_BlackBelt_Text_0, CrownForestNorth_BlackBelt_Text_1
# 27 "data/maps/CrownForestNorth/scripts.pory"
	msgbox CrownForestNorth_BlackBelt_Text_2, MSGBOX_NPC
	return


CrownForestNorth_BattleGirl::
# 31 "data/maps/CrownForestNorth/scripts.pory"
	trainerbattle_single TRAINER_CROWN_NORTH_BATTLEGIRL, CrownForestNorth_BattleGirl_Text_0, CrownForestNorth_BattleGirl_Text_1
# 36 "data/maps/CrownForestNorth/scripts.pory"
	msgbox CrownForestNorth_BattleGirl_Text_2, MSGBOX_NPC
	return


CrownForestNorth_Parasol::
# 40 "data/maps/CrownForestNorth/scripts.pory"
	trainerbattle_single TRAINER_CROWN_NORTH_PARASOL, CrownForestNorth_Parasol_Text_0, CrownForestNorth_Parasol_Text_1
# 45 "data/maps/CrownForestNorth/scripts.pory"
	msgbox CrownForestNorth_Parasol_Text_2, MSGBOX_NPC
	return


CrownForestNorth_BirdKeeper::
# 49 "data/maps/CrownForestNorth/scripts.pory"
	trainerbattle_single TRAINER_CROWN_NORTH_BIRD_KEEPER, CrownForestNorth_BirdKeeper_Text_0, CrownForestNorth_BirdKeeper_Text_1
# 54 "data/maps/CrownForestNorth/scripts.pory"
	msgbox CrownForestNorth_BirdKeeper_Text_2, MSGBOX_NPC
	return


CrownForestNorth_Breeder::
# 58 "data/maps/CrownForestNorth/scripts.pory"
	trainerbattle_single TRAINER_CROWN_NORTH_BREEDER, CrownForestNorth_Breeder_Text_0, CrownForestNorth_Breeder_Text_1
# 63 "data/maps/CrownForestNorth/scripts.pory"
	msgbox CrownForestNorth_Breeder_Text_2, MSGBOX_NPC
	return


CrownForestNorth_AromaLady::
# 67 "data/maps/CrownForestNorth/scripts.pory"
	trainerbattle_single TRAINER_CROWN_NORTH_AROMA_LADY, CrownForestNorth_AromaLady_Text_0, CrownForestNorth_AromaLady_Text_1
# 72 "data/maps/CrownForestNorth/scripts.pory"
	msgbox CrownForestNorth_AromaLady_Text_2, MSGBOX_NPC
	return


CrownForestNorth_BugManiac_Text_0:
# 6 "data/maps/CrownForestNorth/scripts.pory"
	.string "Shh...\nDo you hear that?$"

CrownForestNorth_BugManiac_Text_1:
# 7 "data/maps/CrownForestNorth/scripts.pory"
	.string "I was trying to listen!$"

CrownForestNorth_BugManiac_Text_2:
# 9 "data/maps/CrownForestNorth/scripts.pory"
	.string "I can hear something rustling about in\n"
	.string "the grass...$"

CrownForestNorth_Hiker_Text_0:
# 15 "data/maps/CrownForestNorth/scripts.pory"
	.string "I'm getting soaked!$"

CrownForestNorth_Hiker_Text_1:
# 16 "data/maps/CrownForestNorth/scripts.pory"
	.string "No! My socks got wet!$"

CrownForestNorth_Hiker_Text_2:
# 18 "data/maps/CrownForestNorth/scripts.pory"
	.string "I should've packed an umbrella...$"

CrownForestNorth_BlackBelt_Text_0:
# 24 "data/maps/CrownForestNorth/scripts.pory"
	.string "LET US COMMENCE BATTLE!$"

CrownForestNorth_BlackBelt_Text_1:
# 25 "data/maps/CrownForestNorth/scripts.pory"
	.string "THE BATTLE DIDN'T GO AS PLANNED!$"

CrownForestNorth_BlackBelt_Text_2:
# 27 "data/maps/CrownForestNorth/scripts.pory"
	.string "How's it going?$"

CrownForestNorth_BattleGirl_Text_0:
# 33 "data/maps/CrownForestNorth/scripts.pory"
	.string "If I win you have to drop and give\nme 20!$"

CrownForestNorth_BattleGirl_Text_1:
# 34 "data/maps/CrownForestNorth/scripts.pory"
	.string "Suit yourself, more pushups for me!$"

CrownForestNorth_BattleGirl_Text_2:
# 36 "data/maps/CrownForestNorth/scripts.pory"
	.string "Get a load of these guns!$"

CrownForestNorth_Parasol_Text_0:
# 42 "data/maps/CrownForestNorth/scripts.pory"
	.string "Am I the only person prepared?$"

CrownForestNorth_Parasol_Text_1:
# 43 "data/maps/CrownForestNorth/scripts.pory"
	.string "You may have won, but I'm still dry.\nSo who's the real winner?$"

CrownForestNorth_Parasol_Text_2:
# 45 "data/maps/CrownForestNorth/scripts.pory"
	.string "I'd heard that it rains a lot in here, but\n"
	.string "it really does.$"

CrownForestNorth_BirdKeeper_Text_0:
# 51 "data/maps/CrownForestNorth/scripts.pory"
	.string "Wet wings can still fly!$"

CrownForestNorth_BirdKeeper_Text_1:
# 52 "data/maps/CrownForestNorth/scripts.pory"
	.string "Help! Feathers full of water!$"

CrownForestNorth_BirdKeeper_Text_2:
# 54 "data/maps/CrownForestNorth/scripts.pory"
	.string "Flying types are good against all the\n"
	.string "bugs here.$"

CrownForestNorth_Breeder_Text_0:
# 60 "data/maps/CrownForestNorth/scripts.pory"
	.string "I'm just out for a stroll, care to have\nsome fun?$"

CrownForestNorth_Breeder_Text_1:
# 61 "data/maps/CrownForestNorth/scripts.pory"
	.string "My babies need to expend their energy\nsomehow after all.$"

CrownForestNorth_Breeder_Text_2:
# 63 "data/maps/CrownForestNorth/scripts.pory"
	.string "Even if I lose, battling trainers is a\n"
	.string "good way to exercise.$"

CrownForestNorth_AromaLady_Text_0:
# 69 "data/maps/CrownForestNorth/scripts.pory"
	.string "I'm not really a fan of standing around\nin the rain.$"

CrownForestNorth_AromaLady_Text_1:
# 70 "data/maps/CrownForestNorth/scripts.pory"
	.string "Oh dear...$"

CrownForestNorth_AromaLady_Text_2:
# 72 "data/maps/CrownForestNorth/scripts.pory"
	.string "At least the Rest Area stays dry.$"
