gText_Birch_Welcome::
	.string "Pokemon.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "Oh shi-\p"
	.string "$"

gText_Birch_MainSpeech::
	.string "It's free...\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Get out.\p"
	.string "$"
