DawnshoreCity_Mart_MapScripts::
	.byte 0


DawnshoreCity_Mart_Swimmer::
# 4 "data/maps/DawnshoreCity_Mart/scripts.pory"
	msgbox DawnshoreCity_Mart_Swimmer_Text_0, MSGBOX_NPC
	return


DawnshoreCity_Mart_Woman::
# 8 "data/maps/DawnshoreCity_Mart/scripts.pory"
	msgbox DawnshoreCity_Mart_Woman_Text_0, MSGBOX_NPC
	return


DawnshoreCity_Mart_Boy::
# 12 "data/maps/DawnshoreCity_Mart/scripts.pory"
	msgbox DawnshoreCity_Mart_Boy_Text_0, MSGBOX_NPC
	return


DawnshoreCity_Mart_Swimmer_Text_0:
# 4 "data/maps/DawnshoreCity_Mart/scripts.pory"
	.string "Do you think if I spray a Burn Heal on\n"
	.string "myself it will cure my sunburn?$"

DawnshoreCity_Mart_Woman_Text_0:
# 8 "data/maps/DawnshoreCity_Mart/scripts.pory"
	.string "I like to make sure I'm stocked up on all\n"
	.string "the essentials before I go out on a\l"
	.string "trip!$"

DawnshoreCity_Mart_Boy_Text_0:
# 12 "data/maps/DawnshoreCity_Mart/scripts.pory"
	.string "I will be buying a bunch of Full\n"
	.string "Restores, anything less is\l"
	.string "unacceptable.$"
