DawnshoreCity_MapScripts::
	.byte 0


DawnshoreCity_GymSign::
# 4 "data/maps/DawnshoreCity/scripts.pory"
	msgbox DawnshoreCity_GymSign_Text_0
	return


DawnshoreCity_Man::
# 8 "data/maps/DawnshoreCity/scripts.pory"
	msgbox DawnshoreCity_Man_Text_0, MSGBOX_NPC
	return


DawnshoreCity_Man2::
# 12 "data/maps/DawnshoreCity/scripts.pory"
	msgbox DawnshoreCity_Man2_Text_0, MSGBOX_NPC
	return


DawnshoreCity_FatMan::
# 16 "data/maps/DawnshoreCity/scripts.pory"
	msgbox DawnshoreCity_FatMan_Text_0, MSGBOX_NPC
	return


DawnshoreCity_SwimmerM::
# 20 "data/maps/DawnshoreCity/scripts.pory"
	msgbox DawnshoreCity_SwimmerM_Text_0, MSGBOX_NPC
	return


DawnshoreCity_SwimmerF::
# 24 "data/maps/DawnshoreCity/scripts.pory"
	msgbox DawnshoreCity_SwimmerF_Text_0, MSGBOX_NPC
	return


DawnshoreCity_LittleGirl::
# 28 "data/maps/DawnshoreCity/scripts.pory"
	msgbox DawnshoreCity_LittleGirl_Text_0, MSGBOX_NPC
	return


DawnshoreCity_Woman::
# 32 "data/maps/DawnshoreCity/scripts.pory"
	msgbox DawnshoreCity_Woman_Text_0, MSGBOX_NPC
	return


DawnshoreCity_GymSign_Text_0:
# 4 "data/maps/DawnshoreCity/scripts.pory"
	.string "Dawnshore Gym:\nSun-kissed and Beach ready!$"

DawnshoreCity_Man_Text_0:
# 8 "data/maps/DawnshoreCity/scripts.pory"
	.string "My Loudred has been with me since I was\n"
	.string "a kid, it used to be so cute and quiet...$"

DawnshoreCity_Man2_Text_0:
# 12 "data/maps/DawnshoreCity/scripts.pory"
	.string "They raised the Gym's spot onto a mound\n"
	.string "for some reason.$"

DawnshoreCity_FatMan_Text_0:
# 16 "data/maps/DawnshoreCity/scripts.pory"
	.string "...do you hear a creaking sound?$"

DawnshoreCity_SwimmerM_Text_0:
# 20 "data/maps/DawnshoreCity/scripts.pory"
	.string "I would get up, but I think I'm so\n"
	.string "sunburned I've melted into the chair.$"

DawnshoreCity_SwimmerF_Text_0:
# 24 "data/maps/DawnshoreCity/scripts.pory"
	.string "The sun here is great, I love getting my\n"
	.string "tan on!$"

DawnshoreCity_LittleGirl_Text_0:
# 28 "data/maps/DawnshoreCity/scripts.pory"
	.string "Washu?\p"
	.string "Mapoi!$"

DawnshoreCity_Woman_Text_0:
# 32 "data/maps/DawnshoreCity/scripts.pory"
	.string "Sand makes for a good leg workout, too\n"
	.string "bad it gets all up in everywhere.$"
