HorizonPort_House_MapScripts::
	.byte 0


HorizonPort_House_Man::
# 4 "data/maps/HorizonPort_House/scripts.pory"
	msgbox HorizonPort_House_Man_Text_0, MSGBOX_NPC
	return


HorizonPort_House_Woman::
# 8 "data/maps/HorizonPort_House/scripts.pory"
	msgbox HorizonPort_House_Woman_Text_0, MSGBOX_NPC
	return


HorizonPort_House_Baby::
# 12 "data/maps/HorizonPort_House/scripts.pory"
	msgbox HorizonPort_House_Baby_Text_0, MSGBOX_NPC
	return


HorizonPort_House_Man_Text_0:
# 4 "data/maps/HorizonPort_House/scripts.pory"
	.string "I originally came here for a Pokemon\n"
	.string "journey too, but I've ended up with the\l"
	.string "journey of fatherhood instead.$"

HorizonPort_House_Woman_Text_0:
# 8 "data/maps/HorizonPort_House/scripts.pory"
	.string "And I thought Pokemon were weird.$"

HorizonPort_House_Baby_Text_0:
# 12 "data/maps/HorizonPort_House/scripts.pory"
	.string "?$"
